// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package resource_branch

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/booldefault"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

func BranchResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"branch": schema.StringAttribute{
				Optional: true,
				Computed: true,
			},
			"commit_id": schema.StringAttribute{
				Computed: true,
			},
			"force": schema.BoolAttribute{
				Optional: true,
				Computed: true,
				Default:  booldefault.StaticBool(false),
			},
			"hidden": schema.BoolAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "When set, branch will not show up when listing branches by default. *EXPERIMENTAL*",
				MarkdownDescription: "When set, branch will not show up when listing branches by default. *EXPERIMENTAL*",
				Default:             booldefault.StaticBool(false),
			},
			"id": schema.StringAttribute{
				Computed: true,
			},
			"name": schema.StringAttribute{
				Required:            true,
				Description:         "The name of the branch",
				MarkdownDescription: "The name of the branch",
			},
			"repository": schema.StringAttribute{
				Optional: true,
				Computed: true,
			},
			"source": schema.StringAttribute{
				Required:            true,
				Description:         "Source reference to create the branch from",
				MarkdownDescription: "Source reference to create the branch from",
			},
		},
	}
}

type BranchModel struct {
	Branch     types.String `tfsdk:"branch"`
	CommitId   types.String `tfsdk:"commit_id"`
	Force      types.Bool   `tfsdk:"force"`
	Hidden     types.Bool   `tfsdk:"hidden"`
	Id         types.String `tfsdk:"id"`
	Name       types.String `tfsdk:"name"`
	Repository types.String `tfsdk:"repository"`
	Source     types.String `tfsdk:"source"`
}
