// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package datasource_branch

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
)

func BranchDataSourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"branch": schema.StringAttribute{
				Required: true,
			},
			"commit_id": schema.StringAttribute{
				Computed: true,
			},
			"id": schema.StringAttribute{
				Computed: true,
			},
			"repository": schema.StringAttribute{
				Required: true,
			},
		},
	}
}

type BranchModel struct {
	Branch     types.String `tfsdk:"branch"`
	CommitId   types.String `tfsdk:"commit_id"`
	Id         types.String `tfsdk:"id"`
	Repository types.String `tfsdk:"repository"`
}
