// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package resource_repository

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/booldefault"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"regexp"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

func RepositoryResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"creation_date": schema.Int64Attribute{
				Computed:            true,
				Description:         "Unix Epoch in seconds",
				MarkdownDescription: "Unix Epoch in seconds",
			},
			"default_branch": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "The default branch name (defaults to 'main')",
				MarkdownDescription: "The default branch name (defaults to 'main')",
			},
			"id": schema.StringAttribute{
				Computed: true,
			},
			"name": schema.StringAttribute{
				Required:            true,
				Description:         "The name of the repository",
				MarkdownDescription: "The name of the repository",
				Validators: []validator.String{
					stringvalidator.RegexMatches(regexp.MustCompile("^[a-z0-9][a-z0-9-]{2,62}$"), ""),
				},
			},
			"read_only": schema.BoolAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Whether the repository is a read-only repository- not relevant for bare repositories",
				MarkdownDescription: "Whether the repository is a read-only repository- not relevant for bare repositories",
				Default:             booldefault.StaticBool(false),
			},
			"repository": schema.StringAttribute{
				Optional: true,
				Computed: true,
			},
			"sample_data": schema.BoolAttribute{
				Optional: true,
				Computed: true,
				Default:  booldefault.StaticBool(false),
			},
			"storage_id": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Unique identifier of the underlying data store. *EXPERIMENTAL*",
				MarkdownDescription: "Unique identifier of the underlying data store. *EXPERIMENTAL*",
			},
			"storage_namespace": schema.StringAttribute{
				Required:            true,
				Description:         "Storage namespace URL (e.g., s3://bucket/path, gs://bucket/path, etc.)",
				MarkdownDescription: "Storage namespace URL (e.g., s3://bucket/path, gs://bucket/path, etc.)",
				Validators: []validator.String{
					stringvalidator.RegexMatches(regexp.MustCompile("^(s3|gs|https?|mem|local|transient)://.*$"), ""),
				},
			},
		},
	}
}

type RepositoryModel struct {
	CreationDate     types.Int64  `tfsdk:"creation_date"`
	DefaultBranch    types.String `tfsdk:"default_branch"`
	Id               types.String `tfsdk:"id"`
	Name             types.String `tfsdk:"name"`
	ReadOnly         types.Bool   `tfsdk:"read_only"`
	Repository       types.String `tfsdk:"repository"`
	SampleData       types.Bool   `tfsdk:"sample_data"`
	StorageId        types.String `tfsdk:"storage_id"`
	StorageNamespace types.String `tfsdk:"storage_namespace"`
}
