// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package provider_lakefs

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/provider/schema"
)

func LakefsProviderSchema(ctx context.Context) schema.Schema {
	return schema.Schema{}
}

type LakefsModel struct {
}
