// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package resource_branch_protection

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

func BranchProtectionResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"repository": schema.StringAttribute{
				Optional: true,
				Computed: true,
			},
		},
	}
}

type BranchProtectionModel struct {
	Repository types.String `tfsdk:"repository"`
}
