// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package resource_tag

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/booldefault"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

func TagResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"commit_id": schema.StringAttribute{
				Computed: true,
			},
			"force": schema.BoolAttribute{
				Optional: true,
				Computed: true,
				Default:  booldefault.StaticBool(false),
			},
			"id": schema.StringAttribute{
				Required:            true,
				Description:         "The tag name",
				MarkdownDescription: "The tag name",
			},
			"ref": schema.StringAttribute{
				Required:            true,
				Description:         "The commit reference to tag",
				MarkdownDescription: "The commit reference to tag",
			},
			"repository": schema.StringAttribute{
				Optional: true,
				Computed: true,
			},
			"tag": schema.StringAttribute{
				Optional: true,
				Computed: true,
			},
		},
	}
}

type TagModel struct {
	CommitId   types.String `tfsdk:"commit_id"`
	Force      types.Bool   `tfsdk:"force"`
	Id         types.String `tfsdk:"id"`
	Ref        types.String `tfsdk:"ref"`
	Repository types.String `tfsdk:"repository"`
	Tag        types.String `tfsdk:"tag"`
}
