// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package datasource_repository

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
)

func RepositoryDataSourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"creation_date": schema.Int64Attribute{
				Computed:            true,
				Description:         "Unix Epoch in seconds",
				MarkdownDescription: "Unix Epoch in seconds",
			},
			"default_branch": schema.StringAttribute{
				Computed: true,
			},
			"id": schema.StringAttribute{
				Computed: true,
			},
			"read_only": schema.BoolAttribute{
				Computed:            true,
				Description:         "Whether the repository is a read-only repository- not relevant for bare repositories",
				MarkdownDescription: "Whether the repository is a read-only repository- not relevant for bare repositories",
			},
			"repository": schema.StringAttribute{
				Required: true,
			},
			"storage_id": schema.StringAttribute{
				Computed:            true,
				Description:         "Unique identifier of the underlying data store. *EXPERIMENTAL*",
				MarkdownDescription: "Unique identifier of the underlying data store. *EXPERIMENTAL*",
			},
			"storage_namespace": schema.StringAttribute{
				Computed:            true,
				Description:         "Filesystem URI to store the underlying data in (e.g. \"s3://my-bucket/some/path/\")",
				MarkdownDescription: "Filesystem URI to store the underlying data in (e.g. \"s3://my-bucket/some/path/\")",
			},
		},
	}
}

type RepositoryModel struct {
	CreationDate     types.Int64  `tfsdk:"creation_date"`
	DefaultBranch    types.String `tfsdk:"default_branch"`
	Id               types.String `tfsdk:"id"`
	ReadOnly         types.Bool   `tfsdk:"read_only"`
	Repository       types.String `tfsdk:"repository"`
	StorageId        types.String `tfsdk:"storage_id"`
	StorageNamespace types.String `tfsdk:"storage_namespace"`
}
