// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package datasource_commit

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
)

func CommitDataSourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"commit_id": schema.StringAttribute{
				Required: true,
			},
			"committer": schema.StringAttribute{
				Computed: true,
			},
			"creation_date": schema.Int64Attribute{
				Computed:            true,
				Description:         "Unix Epoch in seconds",
				MarkdownDescription: "Unix Epoch in seconds",
			},
			"generation": schema.Int64Attribute{
				Computed: true,
			},
			"id": schema.StringAttribute{
				Computed: true,
			},
			"message": schema.StringAttribute{
				Computed: true,
			},
			"meta_range_id": schema.StringAttribute{
				Computed: true,
			},
			"metadata": schema.MapAttribute{
				ElementType: types.StringType,
				Computed:    true,
			},
			"parents": schema.ListAttribute{
				ElementType: types.StringType,
				Computed:    true,
			},
			"repository": schema.StringAttribute{
				Required: true,
			},
			"version": schema.Int64Attribute{
				Computed: true,
			},
		},
	}
}

type CommitModel struct {
	CommitId     types.String `tfsdk:"commit_id"`
	Committer    types.String `tfsdk:"committer"`
	CreationDate types.Int64  `tfsdk:"creation_date"`
	Generation   types.Int64  `tfsdk:"generation"`
	Id           types.String `tfsdk:"id"`
	Message      types.String `tfsdk:"message"`
	MetaRangeId  types.String `tfsdk:"meta_range_id"`
	Metadata     types.Map    `tfsdk:"metadata"`
	Parents      types.List   `tfsdk:"parents"`
	Repository   types.String `tfsdk:"repository"`
	Version      types.Int64  `tfsdk:"version"`
}
